name: Workflow Environment
on:
  workflow_dispatch: 
jobs:
  deploy_ambiente:
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Execução do job em ambiente
        run: |
          echo "Variável do ambiente ${{ vars.VAR_AMBIENTE }}"
          echo "Secret do ambiente ${{ secrets.SECRET_AMBIENTE }}"
